version: "2"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'xssplatform'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
  php:
    build: 
      context: ./images/php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./app:/mnt/app

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d
volumes:
  db:
    driver: local
